"""add_created_at_to_user

Revision ID: 3c8636d4ab8d
Revises: 95883054609c
Create Date: 2026-05-23 16:59:44.374190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c8636d4ab8d'
down_revision: Union[str, Sequence[str], None] = '95883054609c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'admin_privilege',
               existing_type=postgresql.ENUM('SUPERADMIN', 'ADMIN', name='adminprivilege'),
               type_=sa.Enum('SUPERADMIN', 'ADMIN', name='adminprivilege', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin_privilege',
               existing_type=sa.Enum('SUPERADMIN', 'ADMIN', name='adminprivilege', native_enum=False),
               type_=postgresql.ENUM('SUPERADMIN', 'ADMIN', name='adminprivilege'),
               existing_nullable=True)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
