"""add_draft_to_status

Revision ID: 5c0333eb55cc
Revises: 6e2104b4f27f
Create Date: 2026-05-13 13:14:30.203455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0333eb55cc'
down_revision: Union[str, Sequence[str], None] = '6e2104b4f27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE status ADD VALUE 'DRAFT'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
