"""add_organization_to_mobile

Revision ID: 92fe1d86a254
Revises: 94b42dcd5424
Create Date: 2026-05-14 11:35:32.528996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fe1d86a254'
down_revision: Union[str, Sequence[str], None] = '94b42dcd5424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobile_workshop_requests', sa.Column('organization', sa.String(length=255), nullable=True))
    op.alter_column('mobile_workshop_requests', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('mobile_workshop_requests', 'region',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('mobile_workshop_requests', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('mobile_workshop_requests', 'purpose',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mobile_workshop_requests', 'purpose',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('mobile_workshop_requests', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('mobile_workshop_requests', 'region',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('mobile_workshop_requests', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('mobile_workshop_requests', 'organization')
    # ### end Alembic commands ###
