"""make_fields_nullable

Revision ID: 94b42dcd5424
Revises: 5c0333eb55cc
Create Date: 2026-05-13 13:22:23.599025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b42dcd5424'
down_revision: Union[str, Sequence[str], None] = '5c0333eb55cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshop_opening_requests', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('workshop_opening_requests', 'region',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('workshop_opening_requests', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('workshop_opening_requests', 'church_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('workshop_opening_requests', 'known_information',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshop_opening_requests', 'known_information',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('workshop_opening_requests', 'church_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('workshop_opening_requests', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('workshop_opening_requests', 'region',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('workshop_opening_requests', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
